sudo: required
dist: trusty

language: python
python: 3.5

install:
  # Install code sniffer.
  - pip install pycodestyle
  - pip install --upgrade pycodestyle
  - source ~/.bash_profile
  - source ~/.bashrc

script:
  # Run code sniffer on the scraper directory.
  - pwd
  - pycodestyle --show-source --max-line-length=119 --exclude=./open_pension_crawler/settings.py --show-pep8 .
